kind = "web"
previewPath = "/backup-api/"
title = "Backup API"
version = "1.0.0"
id = "artifacts/backup-api"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/backup-api/" ]
localPort = 26259

[services.development]
run = "pnpm --filter @workspace/backup-api run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/backup-api", "run", "build" ]
publicDir = "artifacts/backup-api/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26259"
BASE_PATH = "/backup-api/"
